version: 2.1

orbs:
  codecov: codecov/codecov@3.1.0

jobs:
  frontend:
    docker:
      - image: cimg/node:17.4.0-browsers
    working_directory: ~/hamvocke/doppelkopf
    steps:
      - checkout
      - attach_workspace:
          at: ~/hamvocke/doppelkopf
      - restore_cache:
          key: v1-frontend-npm-{{ checksum "package-lock.json" }}
      - run:
          name: Install frontend dependencies
          command: 'npm install'
      - save_cache:
          key: v1-frontend-npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Test frontend
          command: 'npm run test:ci'
      - store_artifacts:
          path: coverage
      - run:
          name: Build frontend
          command: 'npm run build'
      - persist_to_workspace:
          root: .
          paths:
            - dist
      - codecov/upload:
          file: coverage/coverage-final.json
          flags: frontend

workflows:
  version: 2
  build-all-deploy:
    jobs:
      - frontend
